# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvestApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvestApp(object):
    def setupUi(self, InvestApp):
        InvestApp.setObjectName("InvestApp")
        InvestApp.resize(420, 440)
        InvestApp.setMinimumSize(QtCore.QSize(420, 440))
        InvestApp.setBaseSize(QtCore.QSize(400, 400))
        InvestApp.setAccessibleDescription("")
        InvestApp.setAutoFillBackground(False)
        InvestApp.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 180, 137);\n"
"border-top-color: rgb(85, 255, 0);\n"
"gridline-color: rgb(0, 170, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(182, 182, 182);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(InvestApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(420, 420))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.yourApiTokenLabel = QtWidgets.QLabel(self.centralwidget)
        self.yourApiTokenLabel.setMinimumSize(QtCore.QSize(400, 15))
        self.yourApiTokenLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.yourApiTokenLabel.setObjectName("yourApiTokenLabel")
        self.gridLayout.addWidget(self.yourApiTokenLabel, 0, 0, 1, 3)
        self.apiTokenEditField = QtWidgets.QTextEdit(self.centralwidget)
        self.apiTokenEditField.setMinimumSize(QtCore.QSize(400, 40))
        self.apiTokenEditField.setMaximumSize(QtCore.QSize(16777215, 40))
        self.apiTokenEditField.setBaseSize(QtCore.QSize(0, 40))
        self.apiTokenEditField.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.apiTokenEditField.setObjectName("apiTokenEditField")
        self.gridLayout.addWidget(self.apiTokenEditField, 1, 0, 1, 3)
        self.stockNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.stockNameLabel.setMinimumSize(QtCore.QSize(198, 15))
        self.stockNameLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.stockNameLabel.setObjectName("stockNameLabel")
        self.gridLayout.addWidget(self.stockNameLabel, 2, 0, 1, 2)
        self.realStockCostLabel = QtWidgets.QLabel(self.centralwidget)
        self.realStockCostLabel.setMinimumSize(QtCore.QSize(198, 15))
        self.realStockCostLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.realStockCostLabel.setObjectName("realStockCostLabel")
        self.gridLayout.addWidget(self.realStockCostLabel, 2, 2, 1, 1)
        self.stockNameTextEdit = QtWidgets.QComboBox(self.centralwidget)
        self.stockNameTextEdit.setMinimumSize(QtCore.QSize(158, 30))
        self.stockNameTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockNameTextEdit.setObjectName("stockNameTextEdit")
        self.stockNameTextEdit.addItem("")
        self.stockNameTextEdit.addItem("")
        self.stockNameTextEdit.addItem("")
        self.stockNameTextEdit.addItem("")
        self.stockNameTextEdit.addItem("")
        self.gridLayout.addWidget(self.stockNameTextEdit, 3, 0, 1, 1)
        self.uploadStocksNamespushButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadStocksNamespushButton.setMinimumSize(QtCore.QSize(40, 30))
        self.uploadStocksNamespushButton.setStyleSheet("background-color: rgb(74, 214, 163);")
        self.uploadStocksNamespushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadStocksNamespushButton.setIcon(icon)
        self.uploadStocksNamespushButton.setObjectName("uploadStocksNamespushButton")
        self.gridLayout.addWidget(self.uploadStocksNamespushButton, 3, 1, 1, 1)
        self.stockRealCostTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockRealCostTextEdit.setMinimumSize(QtCore.QSize(190, 30))
        self.stockRealCostTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stockRealCostTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockRealCostTextEdit.setObjectName("stockRealCostTextEdit")
        self.gridLayout.addWidget(self.stockRealCostTextEdit, 3, 2, 1, 1)
        self.getCostFromYFPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getCostFromYFPushButton.setMinimumSize(QtCore.QSize(198, 23))
        self.getCostFromYFPushButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.getCostFromYFPushButton.setStyleSheet("background-color: rgb(74, 214, 163);")
        self.getCostFromYFPushButton.setObjectName("getCostFromYFPushButton")
        self.gridLayout.addWidget(self.getCostFromYFPushButton, 4, 0, 1, 3)
        self.amountOfStocksLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountOfStocksLabel.setMinimumSize(QtCore.QSize(198, 15))
        self.amountOfStocksLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.amountOfStocksLabel.setObjectName("amountOfStocksLabel")
        self.gridLayout.addWidget(self.amountOfStocksLabel, 5, 0, 1, 2)
        self.averageCostOfStockLabel = QtWidgets.QLabel(self.centralwidget)
        self.averageCostOfStockLabel.setMinimumSize(QtCore.QSize(198, 15))
        self.averageCostOfStockLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.averageCostOfStockLabel.setObjectName("averageCostOfStockLabel")
        self.gridLayout.addWidget(self.averageCostOfStockLabel, 5, 2, 1, 1)
        self.stockAmountTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockAmountTextEdit.setMinimumSize(QtCore.QSize(195, 30))
        self.stockAmountTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stockAmountTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockAmountTextEdit.setObjectName("stockAmountTextEdit")
        self.gridLayout.addWidget(self.stockAmountTextEdit, 6, 0, 1, 2)
        self.stockAverageTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockAverageTextEdit.setMinimumSize(QtCore.QSize(195, 30))
        self.stockAverageTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stockAverageTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockAverageTextEdit.setObjectName("stockAverageTextEdit")
        self.gridLayout.addWidget(self.stockAverageTextEdit, 6, 2, 1, 1)
        self.calculateEarningPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateEarningPushButton.setMinimumSize(QtCore.QSize(400, 25))
        self.calculateEarningPushButton.setMaximumSize(QtCore.QSize(16777215, 25))
        self.calculateEarningPushButton.setStyleSheet("background-color: rgb(74, 214, 163);")
        self.calculateEarningPushButton.setAutoDefault(False)
        self.calculateEarningPushButton.setDefault(False)
        self.calculateEarningPushButton.setFlat(False)
        self.calculateEarningPushButton.setObjectName("calculateEarningPushButton")
        self.gridLayout.addWidget(self.calculateEarningPushButton, 7, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(400, 15))
        self.line.setMaximumSize(QtCore.QSize(16777215, 15))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 3)
        self.youWillEarnLabel = QtWidgets.QLabel(self.centralwidget)
        self.youWillEarnLabel.setMinimumSize(QtCore.QSize(400, 15))
        self.youWillEarnLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.youWillEarnLabel.setObjectName("youWillEarnLabel")
        self.gridLayout.addWidget(self.youWillEarnLabel, 9, 0, 1, 3)
        self.earningTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.earningTextEdit.setMinimumSize(QtCore.QSize(400, 30))
        self.earningTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.earningTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.earningTextEdit.setObjectName("earningTextEdit")
        self.gridLayout.addWidget(self.earningTextEdit, 10, 0, 1, 3)
        InvestApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InvestApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(0, 0, 0);")
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("selection-background-color: rgb(240, 240, 240);")
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("selection-background-color: rgb(240, 240, 240);")
        self.menuFile.setObjectName("menuFile")
        self.menuTinkoff_API_Token = QtWidgets.QMenu(self.menuFile)
        self.menuTinkoff_API_Token.setObjectName("menuTinkoff_API_Token")
        InvestApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InvestApp)
        self.statusbar.setObjectName("statusbar")
        InvestApp.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(InvestApp)
        self.actionInfo.setObjectName("actionInfo")
        self.actionExport_Token = QtWidgets.QAction(InvestApp)
        self.actionExport_Token.setObjectName("actionExport_Token")
        self.actionGenerate_Key = QtWidgets.QAction(InvestApp)
        self.actionGenerate_Key.setObjectName("actionGenerate_Key")
        self.actionImport = QtWidgets.QAction(InvestApp)
        self.actionImport.setObjectName("actionImport")
        self.actionImport_2 = QtWidgets.QAction(InvestApp)
        self.actionImport_2.setObjectName("actionImport_2")
        self.actionExport = QtWidgets.QAction(InvestApp)
        self.actionExport.setObjectName("actionExport")
        self.actionImport_3 = QtWidgets.QAction(InvestApp)
        self.actionImport_3.setObjectName("actionImport_3")
        self.actionExport_2 = QtWidgets.QAction(InvestApp)
        self.actionExport_2.setObjectName("actionExport_2")
        self.actionImport_4 = QtWidgets.QAction(InvestApp)
        self.actionImport_4.setObjectName("actionImport_4")
        self.actionLoad = QtWidgets.QAction(InvestApp)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(InvestApp)
        self.actionSave.setObjectName("actionSave")
        self.menuHelp.addAction(self.actionInfo)
        self.menuTinkoff_API_Token.addAction(self.actionLoad)
        self.menuTinkoff_API_Token.addAction(self.actionSave)
        self.menuFile.addAction(self.actionGenerate_Key)
        self.menuFile.addAction(self.menuTinkoff_API_Token.menuAction())
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(InvestApp)
        QtCore.QMetaObject.connectSlotsByName(InvestApp)

    def retranslateUi(self, InvestApp):
        _translate = QtCore.QCoreApplication.translate
        InvestApp.setWindowTitle(_translate("InvestApp", "InvestApp"))
        self.yourApiTokenLabel.setText(_translate("InvestApp", "Your API Token:"))
        self.apiTokenEditField.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.stockNameLabel.setText(_translate("InvestApp", "Stock name"))
        self.realStockCostLabel.setText(_translate("InvestApp", "Real stock cost"))
        self.stockNameTextEdit.setItemText(0, _translate("InvestApp", "TAL"))
        self.stockNameTextEdit.setItemText(1, _translate("InvestApp", "VEON"))
        self.stockNameTextEdit.setItemText(2, _translate("InvestApp", "AAPL"))
        self.stockNameTextEdit.setItemText(3, _translate("InvestApp", "GCP"))
        self.stockNameTextEdit.setItemText(4, _translate("InvestApp", "TTP"))
        self.stockRealCostTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6</p></body></html>"))
        self.getCostFromYFPushButton.setText(_translate("InvestApp", "Get data from Tinkoff"))
        self.amountOfStocksLabel.setText(_translate("InvestApp", "Amount of stocks"))
        self.averageCostOfStockLabel.setText(_translate("InvestApp", "Average cost of stock"))
        self.stockAmountTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">100</span></p></body></html>"))
        self.stockAverageTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.31</p></body></html>"))
        self.calculateEarningPushButton.setText(_translate("InvestApp", "Calculate"))
        self.youWillEarnLabel.setText(_translate("InvestApp", "You will earn (in RUB):"))
        self.earningTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10000</p></body></html>"))
        self.menuHelp.setTitle(_translate("InvestApp", "Help"))
        self.menuFile.setTitle(_translate("InvestApp", "File"))
        self.menuTinkoff_API_Token.setTitle(_translate("InvestApp", "Tinkoff API Token"))
        self.actionInfo.setText(_translate("InvestApp", "Info"))
        self.actionExport_Token.setText(_translate("InvestApp", "Export API Token"))
        self.actionGenerate_Key.setText(_translate("InvestApp", "Generate Encryption Key"))
        self.actionImport.setText(_translate("InvestApp", "Import"))
        self.actionImport_2.setText(_translate("InvestApp", "Import"))
        self.actionExport.setText(_translate("InvestApp", "Export"))
        self.actionImport_3.setText(_translate("InvestApp", "Import"))
        self.actionExport_2.setText(_translate("InvestApp", "Export"))
        self.actionImport_4.setText(_translate("InvestApp", "Save"))
        self.actionLoad.setText(_translate("InvestApp", "Import"))
        self.actionSave.setText(_translate("InvestApp", "Export"))
