# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvestApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvestApp(object):
    def setupUi(self, InvestApp):
        InvestApp.setObjectName("InvestApp")
        InvestApp.resize(420, 460)
        InvestApp.setMinimumSize(QtCore.QSize(420, 460))
        InvestApp.setBaseSize(QtCore.QSize(400, 400))
        InvestApp.setAccessibleDescription("")
        InvestApp.setAutoFillBackground(False)
        InvestApp.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 180, 137);\n"
"border-top-color: rgb(85, 255, 0);\n"
"gridline-color: rgb(0, 170, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(182, 182, 182);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(InvestApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(420, 420))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.yourApiTokenLabel = QtWidgets.QLabel(self.centralwidget)
        self.yourApiTokenLabel.setMinimumSize(QtCore.QSize(400, 15))
        self.yourApiTokenLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.yourApiTokenLabel.setObjectName("yourApiTokenLabel")
        self.gridLayout.addWidget(self.yourApiTokenLabel, 0, 0, 1, 2)
        self.apiTokenEditField = QtWidgets.QTextEdit(self.centralwidget)
        self.apiTokenEditField.setMinimumSize(QtCore.QSize(400, 40))
        self.apiTokenEditField.setMaximumSize(QtCore.QSize(16777215, 40))
        self.apiTokenEditField.setBaseSize(QtCore.QSize(0, 40))
        self.apiTokenEditField.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.apiTokenEditField.setObjectName("apiTokenEditField")
        self.gridLayout.addWidget(self.apiTokenEditField, 1, 0, 1, 2)
        self.stockNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.stockNameLabel.setMinimumSize(QtCore.QSize(198, 15))
        self.stockNameLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.stockNameLabel.setObjectName("stockNameLabel")
        self.gridLayout.addWidget(self.stockNameLabel, 2, 0, 1, 1)
        self.realStockCostLabel = QtWidgets.QLabel(self.centralwidget)
        self.realStockCostLabel.setMinimumSize(QtCore.QSize(198, 15))
        self.realStockCostLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.realStockCostLabel.setObjectName("realStockCostLabel")
        self.gridLayout.addWidget(self.realStockCostLabel, 2, 1, 1, 1)
        self.stockNameTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockNameTextEdit.setMinimumSize(QtCore.QSize(198, 30))
        self.stockNameTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stockNameTextEdit.setFont(font)
        self.stockNameTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockNameTextEdit.setObjectName("stockNameTextEdit")
        self.gridLayout.addWidget(self.stockNameTextEdit, 3, 0, 1, 1)
        self.stockRealCostTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockRealCostTextEdit.setMinimumSize(QtCore.QSize(198, 30))
        self.stockRealCostTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stockRealCostTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockRealCostTextEdit.setObjectName("stockRealCostTextEdit")
        self.gridLayout.addWidget(self.stockRealCostTextEdit, 3, 1, 1, 1)
        self.getCostFromYFPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getCostFromYFPushButton.setMinimumSize(QtCore.QSize(198, 23))
        self.getCostFromYFPushButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.getCostFromYFPushButton.setStyleSheet("background-color: rgb(74, 214, 163);")
        self.getCostFromYFPushButton.setObjectName("getCostFromYFPushButton")
        self.gridLayout.addWidget(self.getCostFromYFPushButton, 4, 0, 1, 2)
        self.amountOfStocksLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountOfStocksLabel.setMinimumSize(QtCore.QSize(400, 15))
        self.amountOfStocksLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.amountOfStocksLabel.setObjectName("amountOfStocksLabel")
        self.gridLayout.addWidget(self.amountOfStocksLabel, 5, 0, 1, 2)
        self.stockAmountTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockAmountTextEdit.setMinimumSize(QtCore.QSize(400, 30))
        self.stockAmountTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stockAmountTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockAmountTextEdit.setObjectName("stockAmountTextEdit")
        self.gridLayout.addWidget(self.stockAmountTextEdit, 6, 0, 1, 2)
        self.averageCostOfStockLabel = QtWidgets.QLabel(self.centralwidget)
        self.averageCostOfStockLabel.setMinimumSize(QtCore.QSize(400, 15))
        self.averageCostOfStockLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.averageCostOfStockLabel.setObjectName("averageCostOfStockLabel")
        self.gridLayout.addWidget(self.averageCostOfStockLabel, 7, 0, 1, 2)
        self.stockAverageTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockAverageTextEdit.setMinimumSize(QtCore.QSize(400, 30))
        self.stockAverageTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stockAverageTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.stockAverageTextEdit.setObjectName("stockAverageTextEdit")
        self.gridLayout.addWidget(self.stockAverageTextEdit, 8, 0, 1, 2)
        self.calculateEarningPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateEarningPushButton.setMinimumSize(QtCore.QSize(400, 25))
        self.calculateEarningPushButton.setMaximumSize(QtCore.QSize(16777215, 25))
        self.calculateEarningPushButton.setStyleSheet("background-color: rgb(74, 214, 163);")
        self.calculateEarningPushButton.setAutoDefault(False)
        self.calculateEarningPushButton.setDefault(False)
        self.calculateEarningPushButton.setFlat(False)
        self.calculateEarningPushButton.setObjectName("calculateEarningPushButton")
        self.gridLayout.addWidget(self.calculateEarningPushButton, 9, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(400, 15))
        self.line.setMaximumSize(QtCore.QSize(16777215, 15))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 10, 0, 1, 2)
        self.youWillEarnLabel = QtWidgets.QLabel(self.centralwidget)
        self.youWillEarnLabel.setMinimumSize(QtCore.QSize(400, 15))
        self.youWillEarnLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.youWillEarnLabel.setObjectName("youWillEarnLabel")
        self.gridLayout.addWidget(self.youWillEarnLabel, 11, 0, 1, 2)
        self.earningTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.earningTextEdit.setMinimumSize(QtCore.QSize(400, 30))
        self.earningTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.earningTextEdit.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(0, 0, 0);")
        self.earningTextEdit.setObjectName("earningTextEdit")
        self.gridLayout.addWidget(self.earningTextEdit, 12, 0, 1, 2)
        InvestApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InvestApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(0, 0, 0);")
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.menuHelp.setObjectName("menuHelp")
        InvestApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InvestApp)
        self.statusbar.setObjectName("statusbar")
        InvestApp.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(InvestApp)
        self.actionInfo.setObjectName("actionInfo")
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(InvestApp)
        QtCore.QMetaObject.connectSlotsByName(InvestApp)

    def retranslateUi(self, InvestApp):
        _translate = QtCore.QCoreApplication.translate
        InvestApp.setWindowTitle(_translate("InvestApp", "InvestApp"))
        self.yourApiTokenLabel.setText(_translate("InvestApp", "Your API Token:"))
        self.stockNameLabel.setText(_translate("InvestApp", "Stock name"))
        self.realStockCostLabel.setText(_translate("InvestApp", "Real stock cost"))
        self.stockNameTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TAL</p></body></html>"))
        self.stockRealCostTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6</p></body></html>"))
        self.getCostFromYFPushButton.setText(_translate("InvestApp", "Get real stock cost from Tinkoff API"))
        self.amountOfStocksLabel.setText(_translate("InvestApp", "Amount of stocks"))
        self.stockAmountTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">100</span></p></body></html>"))
        self.averageCostOfStockLabel.setText(_translate("InvestApp", "Average cost of stock"))
        self.stockAverageTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.31</p></body></html>"))
        self.calculateEarningPushButton.setText(_translate("InvestApp", "Calculate"))
        self.youWillEarnLabel.setText(_translate("InvestApp", "You will earn (in RUB):"))
        self.earningTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10000</p></body></html>"))
        self.menuHelp.setTitle(_translate("InvestApp", "Help"))
        self.actionInfo.setText(_translate("InvestApp", "Info"))
