# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvestApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvestApp(object):
    def setupUi(self, InvestApp):
        InvestApp.setObjectName("InvestApp")
        InvestApp.resize(384, 324)
        InvestApp.setAutoFillBackground(False)
        InvestApp.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(InvestApp)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.getCostFromYFPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getCostFromYFPushButton.setGeometry(QtCore.QRect(250, 100, 121, 23))
        self.getCostFromYFPushButton.setObjectName("getCostFromYFPushButton")
        self.youWillEarnLabel = QtWidgets.QLabel(self.centralwidget)
        self.youWillEarnLabel.setGeometry(QtCore.QRect(20, 220, 111, 16))
        self.youWillEarnLabel.setObjectName("youWillEarnLabel")
        self.amountOfStocksLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountOfStocksLabel.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.amountOfStocksLabel.setObjectName("amountOfStocksLabel")
        self.realStockCostLabel = QtWidgets.QLabel(self.centralwidget)
        self.realStockCostLabel.setGeometry(QtCore.QRect(140, 80, 71, 16))
        self.realStockCostLabel.setObjectName("realStockCostLabel")
        self.stockAverageTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockAverageTextEdit.setGeometry(QtCore.QRect(20, 180, 101, 21))
        self.stockAverageTextEdit.setObjectName("stockAverageTextEdit")
        self.calculateEarningPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateEarningPushButton.setGeometry(QtCore.QRect(140, 180, 141, 23))
        self.calculateEarningPushButton.setObjectName("calculateEarningPushButton")
        self.stockNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.stockNameLabel.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.stockNameLabel.setObjectName("stockNameLabel")
        self.averageCostOfStockLabel = QtWidgets.QLabel(self.centralwidget)
        self.averageCostOfStockLabel.setGeometry(QtCore.QRect(20, 160, 111, 16))
        self.averageCostOfStockLabel.setObjectName("averageCostOfStockLabel")
        self.stockAmountTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockAmountTextEdit.setGeometry(QtCore.QRect(20, 140, 101, 21))
        self.stockAmountTextEdit.setObjectName("stockAmountTextEdit")
        self.earningTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.earningTextEdit.setGeometry(QtCore.QRect(20, 250, 251, 21))
        self.earningTextEdit.setObjectName("earningTextEdit")
        self.stockRealCostTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockRealCostTextEdit.setGeometry(QtCore.QRect(140, 100, 101, 21))
        self.stockRealCostTextEdit.setObjectName("stockRealCostTextEdit")
        self.stockNameTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stockNameTextEdit.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stockNameTextEdit.setFont(font)
        self.stockNameTextEdit.setObjectName("stockNameTextEdit")
        self.apiTokenEditField = QtWidgets.QTextEdit(self.centralwidget)
        self.apiTokenEditField.setGeometry(QtCore.QRect(20, 30, 351, 41))
        self.apiTokenEditField.setObjectName("apiTokenEditField")
        self.yourApiTokenLabel = QtWidgets.QLabel(self.centralwidget)
        self.yourApiTokenLabel.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.yourApiTokenLabel.setObjectName("yourApiTokenLabel")
        InvestApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InvestApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        InvestApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InvestApp)
        self.statusbar.setObjectName("statusbar")
        InvestApp.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(InvestApp)
        self.actionInfo.setObjectName("actionInfo")
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(InvestApp)
        QtCore.QMetaObject.connectSlotsByName(InvestApp)
        InvestApp.setTabOrder(self.apiTokenEditField, self.stockNameTextEdit)
        InvestApp.setTabOrder(self.stockNameTextEdit, self.stockAmountTextEdit)
        InvestApp.setTabOrder(self.stockAmountTextEdit, self.stockAverageTextEdit)
        InvestApp.setTabOrder(self.stockAverageTextEdit, self.stockRealCostTextEdit)
        InvestApp.setTabOrder(self.stockRealCostTextEdit, self.getCostFromYFPushButton)
        InvestApp.setTabOrder(self.getCostFromYFPushButton, self.calculateEarningPushButton)
        InvestApp.setTabOrder(self.calculateEarningPushButton, self.earningTextEdit)

    def retranslateUi(self, InvestApp):
        _translate = QtCore.QCoreApplication.translate
        InvestApp.setWindowTitle(_translate("InvestApp", "InvestApp"))
        self.getCostFromYFPushButton.setText(_translate("InvestApp", "Get it from Tinkoff API"))
        self.youWillEarnLabel.setText(_translate("InvestApp", "You will earn (in RUB):"))
        self.amountOfStocksLabel.setText(_translate("InvestApp", "Amount of stocks"))
        self.realStockCostLabel.setText(_translate("InvestApp", "Real stock cost"))
        self.stockAverageTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">100</p></body></html>"))
        self.calculateEarningPushButton.setText(_translate("InvestApp", "Calculate"))
        self.stockNameLabel.setText(_translate("InvestApp", "Stock name"))
        self.averageCostOfStockLabel.setText(_translate("InvestApp", "Average cost of stock"))
        self.stockAmountTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">100</p></body></html>"))
        self.stockRealCostTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.31</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.stockNameTextEdit.setHtml(_translate("InvestApp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">TAL</span></p></body></html>"))
        self.yourApiTokenLabel.setText(_translate("InvestApp", "Your API Token:"))
        self.menuHelp.setTitle(_translate("InvestApp", "Help"))
        self.actionInfo.setText(_translate("InvestApp", "Info"))
